name: Test
on:
    pull_request:
        paths: ['go/**/*.go']
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: '1.22'
            
            - name: Run tests and output to Summary
                    # 1. 標準出力(Console)に詳細を出しつつ、2. 結果をSummaryファイルに追記する
              run: |
                    echo "### Test Results 📋" >> $GITHUB_STEP_SUMMARY
                    echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
                    go test -v ./go/excellent/... >> $GITHUB_STEP_SUMMARY
                    echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
              if: always() # テストが落ちてもレポートを出すために必須
